### ISSUE TITLE
autoconf 2.69 fails to configure 2.25 build

### ISSUE THREAD

**Issue by xihh87** [logological/gpp#14]
I'm building an archlinux package for gpp-2.25.
The source code was taken from https://github.com/logological/gpp/archive/2.25.tar.gz
and the build was made on a clean chroot.

The file corresponds to 7c6c927fde33a43fadbe14c5ab9067742fa72321d6ed95eaae4ae36b269131a0 shasum
and the content are extracted just fine.

The build fails with the folowing error:

```
[builduser@onyx gpp-2.25]$ autoconf
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

If trying to continue ./configure throws an error:

```
[builduser@onyx gpp-2.25]$ ./configure --prefix=/usr --mandir=/usr/share/man
./configure: line 2143: syntax error near unexpected token `ac_config_headers="$ac_config_headers config.h"'
./configure: line 2143: `ac_config_headers="$ac_config_headers config.h"'
```

The documentation also states there should be a config.h.in which I can't find.

```
[builduser@onyx gpp-2.25]$ find
.
./AUTHORS
./COPYING
./COPYING.LESSER
./INSTALL
./Makefile.am
./NEWS
./README.md
./THANKS
./configure.ac
./doc
./doc/Makefile.am
./doc/gpp.pp
./gpp.spec
./src
./src/Makefile.am
./src/gpp.c
./autom4te.cache
./autom4te.cache/requests
./autom4te.cache/traces.0
./autom4te.cache/output.0
./configure
./config.log
```

I attach the config.log (renamed because of github):
[config.txt](https://github.com/logological/gpp/files/752827/config.txt)

**Comment by logological** [comment]
I think the problem is partly on my side and partly on your side.

The problem on your side is that I think you can't just run `autoconf` to generate the `configure` script (and then use this script to build a package).  You need to run something like `aclocal && autoheader && automake --add-missing && autoconf && ./configure && make dist`.

The problem on my side is that I really should be doing all this myself to provide source packages that already include the `configure` script.

**Comment by logological** [comment]
I've added a `make dist` tarball for the latest version of GPP (2.25) to [the GitHub releases page](https://github.com/logological/gpp/releases/tag/2.25).  Note that, as mentioned on the GPP website, such tarballs have always been available from my website at https://files.nothingisreal.com/software/gpp/.  It's just kind of a pain to upload them to GitHub as well, since there is no way to automate this.
